// Top 100 MNC Prep dataset
// Structure mirrors the user's provided JSON. Exported as a const for usage in the Top 100 page.
export const top100Data = {
  Top100MncPrep: {
    "Getting Started": [
      "Introduction to Top 100 codes",
      "ASCII Table",
      "Positive or Negative number",
      "Even or Odd number",
      "Sum of First N Natural numbers",
      "Sum of N natural numbers",
      "Sum of numbers in a given range",
      "Greatest of two numbers",
      "Greatest of the Three numbers",
      "Leap year or not",
      "Prime number",
      "Prime number within a given range",
      "Sum of digits of a number",
      "Reverse of a number",
      "Palindrome number",
      "Armstrong number",
      "Armstrong number in a given range",
      "Fibonacci Series upto nth term",
      "Find the Nth Term of the Fibonacci Series",
      "Factorial of a number",
      "Power of a number",
      "Factor of a number",
      "Finding Prime Factors of a number",
      "Strong number",
      "Perfect number",
      "Perfect Square",
      "Automorphic number",
      "Harshad number",
      "Abundant number",
      "Friendly pair",
    ],
    "Working with Numbers": [
      "Highest Common Factor (HCF)",
      "Lowest Common Multiple (LCM)",
      "Greatest Common Divisor",
      "Binary to Decimal conversion",
      "Octal to Decimal conversion",
      "Hexadecimal to Decimal conversion",
      "Decimal to Binary conversion",
      "Decimal to Octal Conversion",
      "Decimal to Hexadecimal Conversion",
      "Binary to Octal conversion",
      "Octal to Binary conversion",
      "Quadrants in which a given coordinate lies",
      "Permutations (n people, r seats)",
      "Maximum number of handshakes",
      "Addition of two fractions",
      "Replace all 0’s with 1 in a given integer",
      "Can a number be expressed as a sum of two prime numbers",
      "Count possible decoding of a given digit sequence",
      "Calculate the area of a circle",
      "Find the prime numbers between 1 to 100",
      "Calculate the number of digits in an integer",
      "Convert digit/number to words",
      "Counting number of days in a given month of a year",
      "Finding number of times x digit occurs in a given input",
      "Finding number of integers which has exactly x divisors",
      "Finding roots of a quadratic equation",
    ],
    "Codes for Recursion": [
      "Power of a Number",
      "Prime Number",
      "Largest element in an array",
      "Smallest element in an array",
      "Reversing a Number",
      "HCF of two numbers using Recursion",
      "LCM of two numbers",
      "Program to calculate length of the string using recursion",
      "Print All Permutations of a String",
      "Given an integer N, print the F(N)th term",
      "Given a list of N integers, print sums of all subsets",
      "Last non-zero digit in factorial",
      "Given N, return the Nth row of Pascal’s triangle",
      "Generate all combinations of balanced parentheses",
      "Find Factorial using recursion",
      "Find all possible Palindromic partitions of a string",
      "Find all N-bit binary numbers having ≥ as many 1’s as 0’s",
      "Given a set of positive integers, find all subsets",
      "Remove adjacent duplicate characters recursively",
    ],
    "Important Codes related to Arrays": [
      "Find Largest element in an array",
      "Find Smallest element in an array",
      "Find the Smallest and largest element in an array",
      "Find Second Smallest Element in an array",
      "Calculate the sum of elements in an array",
      "Reverse an Array",
      "Sort first half ascending & second half descending",
      "Sort the elements of an array",
      "Finding frequency of elements in an array",
      "Sorting elements of an array by frequency",
      "Finding the Longest Palindrome in an Array",
      "Counting Distinct Elements in an Array",
      "Finding Repeating elements in an Array",
      "Finding Non Repeating elements in an Array",
      "Removing Duplicate elements from an array",
      "Finding Minimum scalar product of two vectors",
      "Finding Maximum scalar product of two vectors in an array",
      "Counting number of even and odd elements in an array",
      "Find all Symmetric pairs in an array",
      "Find maximum product sub-array",
      "Finding if Arrays are disjoint",
      "Determine if array is subset of another array",
      "Determine can all numbers in array be made equal",
      "Finding Minimum sum of absolute difference",
      "Sort array by another array’s order",
      "Replace each element by its rank",
      "Finding equilibrium index",
      "Rotation of elements — left and right",
      "Block swap algorithm for array rotation",
      "Juggling algorithm for array rotation",
      "Circular rotation by K positions",
      "Balanced Parenthesis Problem",
    ],
    "Operations on Strings": [
      "Check whether a character is a vowel or consonant",
      "Check whether a character is alphabet or not",
      "Find ASCII value of a character",
      "Length of the string without strlen()",
      "Toggle each character in a string",
      "Count the number of vowels",
      "Remove the vowels from a String",
      "Check if a string is Palindrome",
      "Print string in reverse order",
      "Remove all characters except alphabets",
      "Remove spaces from a string",
      "Remove brackets from an algebraic expression",
      "Count the sum of numbers in a string",
      "Capitalize first and last character of each word",
      "Calculate frequency of characters in a string",
      "Find non-repeating characters in a string",
      "Check if two strings are Anagram",
      "Replace a substring in a string",
      "Replace a word with another word in a string",
      "Count common subsequence in two strings",
      "Wildcard string match",
      "Print all permutations of a given string in lexicographic order",
    ],
    "Advanced Codes related to Arrays": [
      "Sort array of 0,1,2 without using sorting algorithm",
      "Find Kth max and min element",
      "Move negative elements to one side",
      "Find Union and Intersection of sorted arrays",
      "Largest sum contiguous Subarray",
      "Minimize maximum difference between heights",
      "Minimum number of jumps to reach end",
      "Find duplicate in array of N+1 integers",
      "Merge 2 sorted arrays without extra space",
      "Kadane’s Algorithm",
      "Merge Intervals",
      "Count Inversion",
      "Best time to buy and Sell stock",
      "Find all pairs with sum equal to given number",
      "Find if there is any subarray with sum 0",
      "Find factorial of a large number",
      "Find common elements in 3 sorted arrays",
      "Rearrange array in alternating positive/negative with O(1) space",
      "Find elements that appear more than n/k times",
      "Max profit by buying and selling twice",
      "Next Permutation",
      "Find longest consecutive subsequence",
      "Trapping Rain Water problem",
      "Chocolate Distribution problem",
      "Smallest Subarray with sum greater than given value",
      "Three way partitioning around a value",
      "Minimum operations to make array palindrome",
      "Median of 2 sorted arrays (equal size)",
      "Median of 2 sorted arrays (different size)",
    ],
    "Codes related to Matrix": [
      "Spiral traversal on a Matrix",
      "Search an element in a matrix",
      "Find median in a row-wise sorted matrix",
      "Find row with maximum number of 1’s",
      "Print elements in sorted order from row-col sorted matrix",
      "Find a specific pair in a matrix",
      "Rotate matrix by 90 degrees",
      "Kth smallest element in row-col sorted matrix",
      "Common elements in all rows of a matrix",
    ],
    "Pattern Printing: Star Patterns": [
      "Square Star Pattern (solid)",
      "Hollow Square Star Pattern",
      "Rhombus Star Pattern",
      "Rectangle Star Pattern (solid)",
      "Hollow Rectangle Star Pattern",
      "Parallelogram Star Pattern",
      "Mirrored Rhombus Star Pattern",
      "Triangle Star Pattern (solid)",
      "Pyramid Star Pattern",
      "Hollow Pyramid Star Pattern",
      "Inverted Pyramid Star Pattern",
      "Inverted Hollow Pyramid Star Pattern",
      "Half Diamond Star Pattern",
      "Half Diamond Star Pattern Inverted",
      "Diamond Star Pattern",
    ],
    "Pattern Printing: Number Patterns": [
      "Basic Square 1 Pattern",
      "Basic Square incrementing Pattern",
      "Internal varsity square Pattern",
      "Basic Right Triangle Number Pattern",
      "Basic Right Triangle Number Pattern (Inverted)",
      "Basic incrementing Triangle Pattern (init 3)",
      "Basic incrementing Triangle Pattern (Inverted, init 3)",
      "Basic double incrementing Triangle Pattern (init 3)",
      "Basic incrementing Diamond Pattern (Inverted, init 3)",
      "Basic double incrementing Triangle Pattern (init 3 alternate)",
      "Basic incrementing Triangle Pattern (Mirrored, init 3)",
      "Basic incrementing inverted mirrored Triangle Pattern",
      "Basic incrementing Triangle Pattern + Inverted Mix",
      "Basic Diamond Number Star Pattern",
      "Basic Diamond Number Star Pattern (Sandwich)",
      "Basic Diamond Number Star Pattern (Sandwich Inverted)",
      "Basic Diamond Number Star Pattern (initialized)",
      "Basic Diamond Number Star Pattern (Sandwich)",
      "Basic Diamond Number Star Pattern (Sandwich Inverted)",
    ],
    "Number-Star Mix Patterns": [
      "Basic incrementing Squared Number-Star Pattern",
      "Basic incrementing inverted Squared Number-Star Pattern",
      "Alternate mix of both patterns (Type 2, Type 3)",
      "Basic incrementing Triangle & Inverted Mix (variety of forms)",
      "Basic Diamond Number Star Pattern variants",
    ],
    "Miscellaneous Patterns": [
      "Pyramid star pattern",
      "Pyramid number pattern",
      "Palindromic Pyramid Pattern",
      "Diamond star pattern",
      "Diamond number pattern",
      "Floyd’s Triangle",
      "Pascal triangle",
      "Check array similarity",
      "Square sum program",
      "Longest palindrome in array",
    ],
  },
} as const;
